# Site settings
title: University Portfolio
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: John Rock
user_description: Graduated from Falmouth university and looking to find new opportunities that will help me build and expand my skill set. I have shown myself to be self-motivated, committed and determined in achieving my goals, come what may. I have also demonstrated negotiation and organisation skills, a sense of responsibility and my capacity to work hard under pressure. Prior to university I worked in two local pubs where I learned the value of hard work and was able to build myself up as a person.
user_title: Software Engineer / Games Programmer
email: defiantnarwhal@gmail.com
twitter_username: nrwlx
github_username:  SnugglinBunny 
linkedin_username: DefiantNarwhal
#gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
